// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Event.Models
{
    public partial class Activities
    {
        public Activities()
        {
            ActivityCollections = new HashSet<ActivityCollections>();
            ActivityMembers = new HashSet<ActivityMembers>();
            Questions = new HashSet<Questions>();
        }

        public int Id { get; set; }
        public string CoverImage { get; set; }
        public string ActivityName { get; set; }
        public string Recommendation { get; set; }
        public string Address { get; set; }
        public int MemberLimit { get; set; }
        public int NumOfMember { get; set; }
        public string Description { get; set; }
        public DateTime GatheringTime { get; set; }
        public DateTime Deadline { get; set; }
        public DateTime DateOfCreated { get; set; }
        public int? IstructorId { get; set; }
        public int? CategoryId { get; set; }

        public virtual ActivityCategories Category { get; set; }
        public virtual Instructors Istructor { get; set; }
        public virtual ICollection<ActivityCollections> ActivityCollections { get; set; }
        public virtual ICollection<ActivityMembers> ActivityMembers { get; set; }
        public virtual ICollection<Questions> Questions { get; set; }
    }
}