// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Event.Models
{
    public partial class ActivityMembers
    {
        public int Id { get; set; }
        public int ActivityId { get; set; }
        public int MemberId { get; set; }
        public DateTime DateJoined { get; set; }

        public virtual Activities Activity { get; set; }
        public virtual Members Member { get; set; }
    }
}