// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Event.Models
{
    public partial class Albums
    {
        public Albums()
        {
            AlbumItems = new HashSet<AlbumItems>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int MemberId { get; set; }
        public DateTime CreatedTime { get; set; }

        public virtual Members Member { get; set; }
        public virtual ICollection<AlbumItems> AlbumItems { get; set; }
    }
}