// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Event.Models
{
    public partial class Comments
    {
        public Comments()
        {
            CommentReports = new HashSet<CommentReports>();
        }

        public int Id { get; set; }
        public string Content { get; set; }
        public DateTime CommentTime { get; set; }
        public int? PhotoId { get; set; }
        public int? MemberId { get; set; }

        public virtual Members Member { get; set; }
        public virtual Photos Photo { get; set; }
        public virtual ICollection<CommentReports> CommentReports { get; set; }
    }
}