// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Event.Models
{
    public partial class FollowInfos
    {
        public int Follower { get; set; }
        public int Following { get; set; }
        public DateTime FollowTime { get; set; }

        public virtual Members FollowerNavigation { get; set; }
        public virtual Members FollowingNavigation { get; set; }
    }
}