// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Event.Models
{
    public partial class IndiscriminateReports
    {
        public int MemberId { get; set; }
        public int? NumOfTimes { get; set; }
    }
}