// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Event.Models
{
    public partial class Members
    {
        public Members()
        {
            ActivityCollections = new HashSet<ActivityCollections>();
            ActivityMembers = new HashSet<ActivityMembers>();
            Albums = new HashSet<Albums>();
            CommentReports = new HashSet<CommentReports>();
            Comments = new HashSet<Comments>();
            FollowInfosFollowerNavigation = new HashSet<FollowInfos>();
            FollowInfosFollowingNavigation = new HashSet<FollowInfos>();
            OrderDetails = new HashSet<OrderDetails>();
            OthersCollections = new HashSet<OthersCollections>();
            OwnCollections = new HashSet<OwnCollections>();
            PhotoReports = new HashSet<PhotoReports>();
            Photos = new HashSet<Photos>();
            Questions = new HashSet<Questions>();
            ShoppingCarts = new HashSet<ShoppingCarts>();
            Views = new HashSet<Views>();
            Coupon = new HashSet<Coupons>();
            Product = new HashSet<Products>();
        }

        public int Id { get; set; }
        public string EmailAccount { get; set; }
        public string EncryptedPassword { get; set; }
        public string RealName { get; set; }
        public string NickName { get; set; }
        public DateTime? BirthOfDate { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string PhotoSticker { get; set; }
        public string About { get; set; }
        public string ConfirmCode { get; set; }
        public bool IsConfirmed { get; set; }
        public bool IsInBlackList { get; set; }

        public virtual ICollection<ActivityCollections> ActivityCollections { get; set; }
        public virtual ICollection<ActivityMembers> ActivityMembers { get; set; }
        public virtual ICollection<Albums> Albums { get; set; }
        public virtual ICollection<CommentReports> CommentReports { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual ICollection<FollowInfos> FollowInfosFollowerNavigation { get; set; }
        public virtual ICollection<FollowInfos> FollowInfosFollowingNavigation { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual ICollection<OthersCollections> OthersCollections { get; set; }
        public virtual ICollection<OwnCollections> OwnCollections { get; set; }
        public virtual ICollection<PhotoReports> PhotoReports { get; set; }
        public virtual ICollection<Photos> Photos { get; set; }
        public virtual ICollection<Questions> Questions { get; set; }
        public virtual ICollection<ShoppingCarts> ShoppingCarts { get; set; }
        public virtual ICollection<Views> Views { get; set; }

        public virtual ICollection<Coupons> Coupon { get; set; }
        public virtual ICollection<Products> Product { get; set; }
    }
}