// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Event.Models
{
    public partial class PhotoReports
    {
        public int Id { get; set; }
        public int? Reporter { get; set; }
        public int PhotoId { get; set; }
        public DateTime ReportTime { get; set; }

        public virtual Photos Photo { get; set; }
        public virtual Members ReporterNavigation { get; set; }
    }
}