// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Event.Models
{
    public partial class Photos
    {
        public Photos()
        {
            AlbumItems = new HashSet<AlbumItems>();
            Comments = new HashSet<Comments>();
            OthersCollections = new HashSet<OthersCollections>();
            OwnCollections = new HashSet<OwnCollections>();
            PhotoReports = new HashSet<PhotoReports>();
            Views = new HashSet<Views>();
            Tag = new HashSet<Tags>();
        }

        public int Id { get; set; }
        public string Source { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int Author { get; set; }
        public int? Iso { get; set; }
        public string Pixel { get; set; }
        public string Aperture { get; set; }
        public string Shutter { get; set; }
        public string Camera { get; set; }
        public string Negative { get; set; }
        public string Location { get; set; }
        public DateTime ShootingTime { get; set; }
        public DateTime UploadTime { get; set; }

        public virtual Members AuthorNavigation { get; set; }
        public virtual ICollection<AlbumItems> AlbumItems { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual ICollection<OthersCollections> OthersCollections { get; set; }
        public virtual ICollection<OwnCollections> OwnCollections { get; set; }
        public virtual ICollection<PhotoReports> PhotoReports { get; set; }
        public virtual ICollection<Views> Views { get; set; }

        public virtual ICollection<Tags> Tag { get; set; }
    }
}