// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Event.Models
{
    public partial class Questions
    {
        public Questions()
        {
            Answers = new HashSet<Answers>();
        }

        public int Id { get; set; }
        public string Content { get; set; }
        public DateTime DateCreated { get; set; }
        public int ActivityId { get; set; }
        public int MemberId { get; set; }

        public virtual Activities Activity { get; set; }
        public virtual Members Member { get; set; }
        public virtual ICollection<Answers> Answers { get; set; }
    }
}