// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Event.Models
{
    public partial class Tags
    {
        public Tags()
        {
            Photo = new HashSet<Photos>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime CreatedTime { get; set; }

        public virtual ICollection<Photos> Photo { get; set; }
    }
}