// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ProjectFUEN.Models.DTOs;
using ProjectFUEN.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ProjectFUEN.Models.EFModels
{
    public partial class ActivityCategory
    {
        public ActivityCategory()
        {
            Activities = new HashSet<Activity>();
        }

        public int Id { get; set; }
        [Display(Name ="顯示順序")]
		[Required]
		public int DisplayOrder { get; set; }

		[Required]
		[StringLength(50)]
		[Display(Name = "類型名稱")]
		public string CategoryName { get; set; }


		public virtual ICollection<Activity> Activities { get; set; }
    }
	public static partial class ActivityCategoryExts
	{
		public static ActivityCategory ToEntity(this ActivityCategoryDto source)
		{
			return new ActivityCategory
			{
				Id = source.Id,
				DisplayOrder = source.DisplayOrder,
				CategoryName = source.CategoryName,
			};
		}
	}
}