// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ProjectFUEN.Models.DTOs;
using System;
using System.Collections.Generic;

namespace ProjectFUEN.Models.EFModels
{
    public partial class ActivityCategory
    {
        public ActivityCategory()
        {
            Activities = new HashSet<Activity>();
        }

        public int Id { get; set; }
        public int DisplayOrder { get; set; }
        public string CategoryName { get; set; }

        public virtual ICollection<Activity> Activities { get; set; }
    }
    public static partial class ActivityCategoryExts
    {
        public static ActivityCategory ToEntity(this ActivityCategoryDto source)
        {
            return new ActivityCategory
            {
                Id = source.Id,
                DisplayOrder = source.DisplayOrder,
                CategoryName = source.CategoryName,
            };
        }
    }
}