// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ProjectFUEN.Models.ViewModels;
using System;
using System.Collections.Generic;

namespace ProjectFUEN.Models.EFModels
{
    public partial class Event
    {
        public Event()
        {
            Products = new HashSet<Product>();
        }

        public int Id { get; set; }
        public string EventName { get; set; }
        public string Photo { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }

        public virtual ICollection<Product> Products { get; set; }
    }

    public static partial class EventExts
    {
        public static Event ToEntity(this EventVM source)
        {
            return new Event
            {
                Id = source.Id,
                EventName = source.EventName,
                Photo = source.Photo,
                StartDate = source.StartDate,
                EndDate = source.EndDate
            };
        }
    }
}