// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectFUEN.Models.EFModels
{
    public partial class Member
    {
        public Member()
        {
            CommentReports = new HashSet<CommentReport>();
            Comments = new HashSet<Comment>();
            PhotoReports = new HashSet<PhotoReport>();
            Photos = new HashSet<Photo>();
        }

        public int Id { get; set; }
        public string EmailAccount { get; set; }
        public string EncryptedPassword { get; set; }
        public string RealName { get; set; }
        public string NickName { get; set; }
        public DateTime? BirthOfDate { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string PhotoSticker { get; set; }
        public string About { get; set; }
        public string ConfirmCode { get; set; }
        public bool IsConfirmed { get; set; }
        public bool IsInBlackList { get; set; }

        public virtual ICollection<CommentReport> CommentReports { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<PhotoReport> PhotoReports { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
    }
}