// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace ProjectFUEN.Models.EFModels
{
    public partial class OrderDetail
    {
        public OrderDetail()
        {
            OrderItems = new HashSet<OrderItem>();
        }

        public int Id { get; set; }
        public int MemberId { get; set; }
        [Display(Name = "訂單日期")]
        public DateTime OrderDate { get; set; }
        [Display(Name = "地址")]
        public string Address { get; set; }
        [Display(Name = "訂單狀態")]
        public int State { get; set; }

        public virtual Member Member { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}