// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectFUEN.Models.EFModels
{
    public partial class Photo
    {
        public int Id { get; set; }
        public string Source { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int Author { get; set; }
        public int? ISO { get; set; }
        public string Pixel { get; set; }
        public string Camera { get; set; }
        public string Negative { get; set; }
        public int? FocalLength { get; set; }
        public string Shutter { get; set; }
        public string Location { get; set; }
        public DateTime ShootingTime { get; set; }
        public DateTime UploadTime { get; set; }

        public virtual Member AuthorNavigation { get; set; }
    }
}