// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductsBackStage.EFModels
{
    public partial class Coupons
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public decimal Discount { get; set; }
        public int LeastCost { get; set; }
        public int Count { get; set; }
    }
}