// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductsBackStage.EFModels
{
    public partial class Events
    {
        public Events()
        {
            Product = new HashSet<Products>();
        }

        public int Id { get; set; }
        public string EventName { get; set; }
        public string Photo { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }

        public virtual ICollection<Products> Product { get; set; }
    }
}