// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductsBackStage.EFModels
{
    public partial class ProductPhotos
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string Source { get; set; }

        public virtual Products Product { get; set; }
    }
}