// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductsBackStage.EFModels
{
    public partial class Products
    {
        public Products()
        {
            OrderItems = new HashSet<OrderItems>();
            ProductPhotos = new HashSet<ProductPhotos>();
            ShoppingCarts = new HashSet<ShoppingCarts>();
            Event = new HashSet<Events>();
            Member = new HashSet<Members>();
        }

        public int Id { get; set; }
        public int CategoryId { get; set; }
        public int BrandId { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public DateTime ManufactorDate { get; set; }
        public DateTime ReleaseDate { get; set; }
        public int Inventory { get; set; }
        public string ProductSpec { get; set; }

        public virtual Brands Brand { get; set; }
        public virtual Categories Category { get; set; }
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual ICollection<ProductPhotos> ProductPhotos { get; set; }
        public virtual ICollection<ShoppingCarts> ShoppingCarts { get; set; }

        public virtual ICollection<Events> Event { get; set; }
        public virtual ICollection<Members> Member { get; set; }
    }
}